name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK from Web App
        uses: subhash3/web-to-apk-action@v1
        with:
          appName: 'MyApp'
          appUrl: 'https://github.com'

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: '**/*.apk'
